data_entries = [
    ("What time is it?", 1),
    ("Where are you going?", 1),
    ("Can you help me?", 1),
    ("How does this work?", 1),
    ("Why is the sky blue?", 1),
    ("What is your name?", 1),
    ("How do I fix this issue?", 1),
    ("When is the next bus?", 1),
    ("What's the weather like?", 1),
    ("What is the meaning of life?", 1),
    ("How do I start learning Python?", 1),
    ("Tell me a joke!", 1),
    ("What is your favorite book?", 1),
    ("Can you recommend a good movie?", 1),
    ("What is the capital of France?", 1),
    ("Where can I buy a new phone?", 1),
    ("How do I reset my password?", 1),
    ("What time does the movie start?", 1),
    ("What's your opinion on AI?", 1),
    ("Do you know any fun facts?", 1),
    ("What is the speed of light?", 1),
    ("How can I improve my productivity?", 1),
    ("Can you explain quantum mechanics?", 1),
    ("What is the largest planet in our solar system?", 1),
    ("Who was the first president of the United States?", 1),
    ("Where can I find free online courses?", 1),
    ("What is the weather forecast for tomorrow?", 1),
    ("Is there life on Mars?", 1),
    ("What are the benefits of meditation?", 1),
    ("How do I grow a plant?", 1),
    ("What is the best way to lose weight?", 1),
    ("Do aliens exist?", 1),
    ("How do I change a tire?", 1),
    ("What is the population of Japan?", 1),
    ("Can you solve this math problem?", 1),
    ("When did the internet start?", 1),
    ("Where is the nearest coffee shop?", 1),
    ("What is your favorite food?", 1),
    ("How does gravity work?", 1),
    ("Why do we dream?", 1),
    ("What causes rainbows?", 1),
    ("Can I learn guitar online?", 1),
    ("When is the next holiday?", 1),
    ("What's your favorite movie?", 1),
    ("Where is the Eiffel Tower?", 1),
    ("Why do cats purr?", 1),
    ("What is machine learning?", 1),
    ("How do I start a blog?", 1),
    ("What are black holes?", 1),
    ("Where can I get good pizza?", 1),
    ("Can I travel with my pet?", 1),
    ("What is the tallest mountain?", 1),
    ("How do airplanes fly?", 1),
    ("What’s the fastest animal?", 1),
    ("Where do penguins live?", 1),
    ("Can you tell me a fun riddle?", 1),
    ("Why do we yawn?", 1),

    ("I am going to the store.", 0),
    ("The sun is shining.", 0),
    ("She loves painting.", 0),
    ("I watched a movie last night.", 0),
    ("He is my brother.", 0),
    ("The earth revolves around the sun.", 0),
    ("Cats make great pets.", 0),
    ("I am learning Python programming.", 0),
    ("I had pizza for dinner.", 0),
    ("It is a beautiful day.", 0),
    ("My favorite color is blue.", 0),
    ("I read books in my free time.", 0),
    ("She is a great singer.", 0),
    ("The book is on the table.", 0),
    ("I just finished my homework.", 0),
    ("I went for a walk this morning.", 0),
    ("I enjoy playing video games.", 0),
    ("He is studying to be a doctor.", 0),
    ("My parents are going on vacation next month.", 0),
    ("I learned how to cook pasta today.", 0),
    ("She loves listening to music.", 0),
    ("I am excited for the weekend.", 0),
    ("My dog loves to play fetch.", 0),
    ("I am reading a mystery novel.", 0),
    ("I like to exercise in the morning.", 0),
    ("The restaurant has great food.", 0),
    ("I have two younger siblings.", 0),
    ("We are planning a road trip next summer.", 0),
    ("I recently got a new phone.", 0),
    ("The train leaves at 6 PM.", 0),
    ("I enjoy learning about history.", 0),
    ("She is really good at drawing.", 0),
    ("We are going to the beach this weekend.", 0),
    ("I have a meeting at 2 PM.", 0),
    ("I love watching documentaries.", 0),
    ("I can't wait for the holidays.", 0),
    ("I visited a museum yesterday.", 0),
    ("He plays the guitar very well.", 0),
    ("I cleaned my room today.", 0),
    ("The dog is sleeping on the couch.", 0),
    ("She made a delicious cake.", 0),
    ("He is playing soccer with his friends.", 0),
    ("The movie was really interesting.", 0),
    ("I had coffee this morning.", 0),
    ("We went hiking over the weekend.", 0),
    ("The kids are watching cartoons.", 0),
    ("He finished his science project.", 0),
    ("She wore a red dress to the party.", 0),
    ("The baby is laughing happily.", 0),
    ("I saw a rainbow yesterday.", 0),
    ("We celebrated his birthday at home.", 0),
    ("The garden looks beautiful in spring.", 0),
    ("I sent the email an hour ago.", 0),
    ("She painted a landscape in watercolor.", 0),
    ("The store is closed on Sundays.", 0),
    ("I listen to podcasts while jogging.", 0),
    ("He drives a red sports car.", 0),
    ("My cousin is visiting us next week.", 0),
    ("I made pancakes for breakfast.", 0),
    ("We watched the stars last night.", 0),
    ("The book was better than the movie.", 0),
    ("I wrote in my journal this morning.", 0),
    ("She adopted a cat last weekend.", 0)
]